# Generated by Django 4.2 on 2025-05-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_visit',
            field=models.IntegerField(default=0),
        ),
    ]
