# Generated by Django 4.2 on 2025-04-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='No address provided', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='Not Specified', max_length=20),
        ),
    ]
