# Generated by Django 4.2 on 2025-05-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorManagement', '0002_alter_doctor_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doc_num',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile',
            field=models.ImageField(upload_to='doctor_profiles/'),
        ),
    ]
