# Generated by Django 4.2 on 2025-05-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorManagement', '0003_doctor_doc_num_alter_doctor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Endocrinology', 'Endocrinology'), ('ENT', 'ENT'), ('Gynecology', 'Gynecology'), ('Neurology', 'Neurology'), ('Oncology', 'Oncology'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Psychiatry', 'Psychiatry'), ('Radiology', 'Radiology')], max_length=100),
        ),
    ]
