# Generated by Django 4.2 on 2025-05-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorManagement', '0004_alter_doctor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_num',
            field=models.CharField(max_length=10),
        ),
    ]
